---
  - hosts: all
    gather_facts: yes

  - hosts: HAproxy
    become: yes
    tasks:
      - name: Install HAproxy
        become: yes
        apt:
          name: haproxy

          state: present

      - name: Configuring HAproxy to use as a load balancer
        template:
           src: haproxy.cfg.j2
           dest: /etc/haproxy/haproxy.cfg
    
      - name: "restarting haproxy services"
        service:
                name: "haproxy"
                state: started

  - name: deploy flask app
    hosts: webservers
    become: yes
    tasks:
      - name: update apt cache
        apt:
          update_cache: yes

      - name: Install Python3
        apt:
          state: latest

      - name: install  python3-pip
        apt:
          state: latest

      - name: installing virtual environment python3-venv
        become: yes
        apt:
          name: python3-venv
          state: latest

      - name: Create Flask app directory
        file:
          path: /home/ubuntu/flask-app
          state: directory
          owner: ubuntu
          group: ubuntu
          
      - name: Install Flask
        become: yes
        pip:
          name: flask
          state: latest
          
      - name: change directory
        shell: cd /home/ubuntu/flask-app

      - name: Create virtual environment
        command: python3 -m venv /home/ubuntu/venv

      - name: Activate virtual environment
        shell: . /home/ubuntu/flask-app/venv/bin/activate


      - name: copy flask file
        copy:
          src: app.py
          dest: /home/ubuntu/flask-app/app.py
          mode: '0755'


      - name: Start and execute Flask app
        shell: flask run -h 0.0.0.0 -p 5000
        async: 500
        poll: 0


  - hosts: HAproxy
    become: yes
    tasks:
      -  name: "restarting haproxy services"
         service:
                name: "haproxy"
                state: started
        

 
