---
  - hosts: all
    gather_facts: yes

  - hosts: HAproxy
    become: yes
    tasks:
      - name: Install HAproxy
        apt:
          name: haproxy
          update_cache: yes
          state: present

      - name: Configuring HAproxy to use as a load balancer
        copy:
           src: /haproxy.cfg
           dest: /etc/haproxy/haproxy.cfg
        notify: Restart haproxy

    handlers:
           - name: restart haproxy
             systemd:
                   name: haproxy
                   state: restarted

  - hosts: webservers
    remote_user: ubuntu
    become: yes
    tasks:
      - name: update the system
        apt:
          update_cache: yes

      - name: installing python3
        apt:
          state: latest

      - name: installing python3-pip
        apt:
          state: latest

      - name: installing python3-venv
        apt:
          state: latest


      - name: create virtual environment
        apt:


      - name: Copy Flask app files
        copy:
           src: app.py
           dest: /home/ubuntu
        tags:
            - flask


